/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { IEvents, IEventsInterface } from "../IEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "nodeType",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "string",
        name: "attribute",
        type: "string",
      },
    ],
    name: "AttributeAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "nodeType",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "nodeId",
        type: "uint256",
      },
    ],
    name: "NodeMinted",
    type: "event",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea26469706673582212208c8d42ec36b746eb9911140f90fbf6eecaeb5ff9c9a0fae91f0266644aa1b9af64736f6c634300080d0033";

export class IEvents__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<IEvents> {
    return super.deploy(overrides || {}) as Promise<IEvents>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): IEvents {
    return super.attach(address) as IEvents;
  }
  connect(signer: Signer): IEvents__factory {
    return super.connect(signer) as IEvents__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): IEventsInterface {
    return new utils.Interface(_abi) as IEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEvents {
    return new Contract(address, _abi, signerOrProvider) as IEvents;
  }
}
