/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface VehicleInterface extends ethers.utils.Interface {
  functions: {
    "addVehicleAttribute(string)": FunctionFragment;
    "mintVehicle(uint256,address,string[],string[])": FunctionFragment;
    "mintVehicleSign(uint256,address,string[],string[],bytes)": FunctionFragment;
    "setVehicleInfo(uint256,string[],string[])": FunctionFragment;
    "setVehicleNodeType(bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addVehicleAttribute",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "mintVehicle",
    values: [BigNumberish, string, string[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "mintVehicleSign",
    values: [BigNumberish, string, string[], string[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVehicleInfo",
    values: [BigNumberish, string[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setVehicleNodeType",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addVehicleAttribute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintVehicle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintVehicleSign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVehicleInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVehicleNodeType",
    data: BytesLike
  ): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "ApprovalForAll(address,address,bool)": EventFragment;
    "AttributeAdded(uint256,string)": EventFragment;
    "NodeMinted(uint256,uint256)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ApprovalForAll"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AttributeAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NodeMinted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
}

export type ApprovalEvent = TypedEvent<
  [string, string, BigNumber] & {
    owner: string;
    operator: string;
    tokenId: BigNumber;
  }
>;

export type ApprovalForAllEvent = TypedEvent<
  [string, string, boolean] & {
    owner: string;
    operator: string;
    approved: boolean;
  }
>;

export type AttributeAddedEvent = TypedEvent<
  [BigNumber, string] & { nodeType: BigNumber; attribute: string }
>;

export type NodeMintedEvent = TypedEvent<
  [BigNumber, BigNumber] & { nodeType: BigNumber; nodeId: BigNumber }
>;

export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string] & {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
>;

export type RoleGrantedEvent = TypedEvent<
  [string, string, string] & { role: string; account: string; sender: string }
>;

export type RoleRevokedEvent = TypedEvent<
  [string, string, string] & { role: string; account: string; sender: string }
>;

export type TransferEvent = TypedEvent<
  [string, string, BigNumber] & { from: string; to: string; tokenId: BigNumber }
>;

export class Vehicle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: VehicleInterface;

  functions: {
    addVehicleAttribute(
      attribute: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mintVehicle(
      rootNode: BigNumberish,
      _owner: string,
      attributes: string[],
      infos: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mintVehicleSign(
      rootNode: BigNumberish,
      _owner: string,
      attributes: string[],
      infos: string[],
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setVehicleInfo(
      nodeId: BigNumberish,
      attributes: string[],
      infos: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setVehicleNodeType(
      label: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addVehicleAttribute(
    attribute: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mintVehicle(
    rootNode: BigNumberish,
    _owner: string,
    attributes: string[],
    infos: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mintVehicleSign(
    rootNode: BigNumberish,
    _owner: string,
    attributes: string[],
    infos: string[],
    signature: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setVehicleInfo(
    nodeId: BigNumberish,
    attributes: string[],
    infos: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setVehicleNodeType(
    label: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addVehicleAttribute(
      attribute: string,
      overrides?: CallOverrides
    ): Promise<void>;

    mintVehicle(
      rootNode: BigNumberish,
      _owner: string,
      attributes: string[],
      infos: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    mintVehicleSign(
      rootNode: BigNumberish,
      _owner: string,
      attributes: string[],
      infos: string[],
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setVehicleInfo(
      nodeId: BigNumberish,
      attributes: string[],
      infos: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    setVehicleNodeType(
      label: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Approval(address,address,uint256)"(
      owner?: string | null,
      operator?: string | null,
      tokenId?: BigNumberish | null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { owner: string; operator: string; tokenId: BigNumber }
    >;

    Approval(
      owner?: string | null,
      operator?: string | null,
      tokenId?: BigNumberish | null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { owner: string; operator: string; tokenId: BigNumber }
    >;

    "ApprovalForAll(address,address,bool)"(
      owner?: string | null,
      operator?: string | null,
      approved?: null
    ): TypedEventFilter<
      [string, string, boolean],
      { owner: string; operator: string; approved: boolean }
    >;

    ApprovalForAll(
      owner?: string | null,
      operator?: string | null,
      approved?: null
    ): TypedEventFilter<
      [string, string, boolean],
      { owner: string; operator: string; approved: boolean }
    >;

    "AttributeAdded(uint256,string)"(
      nodeType?: BigNumberish | null,
      attribute?: string | null
    ): TypedEventFilter<
      [BigNumber, string],
      { nodeType: BigNumber; attribute: string }
    >;

    AttributeAdded(
      nodeType?: BigNumberish | null,
      attribute?: string | null
    ): TypedEventFilter<
      [BigNumber, string],
      { nodeType: BigNumber; attribute: string }
    >;

    "NodeMinted(uint256,uint256)"(
      nodeType?: BigNumberish | null,
      nodeId?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { nodeType: BigNumber; nodeId: BigNumber }
    >;

    NodeMinted(
      nodeType?: BigNumberish | null,
      nodeId?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { nodeType: BigNumber; nodeId: BigNumber }
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; previousAdminRole: string; newAdminRole: string }
    >;

    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; previousAdminRole: string; newAdminRole: string }
    >;

    "RoleGranted(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    "RoleRevoked(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    "Transfer(address,address,uint256)"(
      from?: string | null,
      to?: string | null,
      tokenId?: BigNumberish | null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { from: string; to: string; tokenId: BigNumber }
    >;

    Transfer(
      from?: string | null,
      to?: string | null,
      tokenId?: BigNumberish | null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { from: string; to: string; tokenId: BigNumber }
    >;
  };

  estimateGas: {
    addVehicleAttribute(
      attribute: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mintVehicle(
      rootNode: BigNumberish,
      _owner: string,
      attributes: string[],
      infos: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mintVehicleSign(
      rootNode: BigNumberish,
      _owner: string,
      attributes: string[],
      infos: string[],
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setVehicleInfo(
      nodeId: BigNumberish,
      attributes: string[],
      infos: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setVehicleNodeType(
      label: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addVehicleAttribute(
      attribute: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mintVehicle(
      rootNode: BigNumberish,
      _owner: string,
      attributes: string[],
      infos: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mintVehicleSign(
      rootNode: BigNumberish,
      _owner: string,
      attributes: string[],
      infos: string[],
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setVehicleInfo(
      nodeId: BigNumberish,
      attributes: string[],
      infos: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setVehicleNodeType(
      label: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
